#!/usr/bin/env bash


downloaddir=$1
if [ -z $1 ]; then
    mkdir archiso_download
    downloaddir=archiso_download
fi


function download {
    cd $downloaddir
    
    wget -q https://geo.mirror.pkgbuild.com/iso/latest/archlinux-x86_64.iso
    wget -q https://geo.mirror.pkgbuild.com/iso/latest/archlinux-x86_64.iso.sig
    wget -q https://geo.mirror.pkgbuild.com/iso/latest/b2sums.txt
    wget -q https://geo.mirror.pkgbuild.com/iso/latest/sha256sums.txt

    echo 'Download complete.'
}


function verify {
    cd $downloaddir

    for file in ./*; do
        grep $file sha256sums.txt >> real256sums.txt
    done

    sha256sum -c real256sums.txt
    rm real256sums.txt

    gpg -q --auto-key-locate clear,wkd -v --locate-external-key pierre@archlinux.org 2>/dev/null 1>/dev/null
    gpg -q --keyserver-options auto-key-retrieve --verify archlinux-x86_64.iso.sig archlinux-x86_64.iso 2>/dev/null 1>/dev/null

    if [ $? -ne 0 ]; then
        echo 'Something has gone horribly wrong. Do not trust these images!'
    else
        echo 'They are old signatures, but they check out.'
    fi
}


function main {
    download
    verify
}


main
